// <auto-generated />
using System;
using EmployeeManagement.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeManagement.DAL.Migrations
{
    [DbContext(typeof(EmployeeManagementDbContext))]
    partial class EmployeeManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeManagement.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-3333-4444-555555555555"),
                            Birthday = new DateTime(1990, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Ion Ionescu"
                        },
                        new
                        {
                            Id = new Guid("a1111111-2222-3333-4444-555555555555"),
                            Birthday = new DateTime(1990, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Ana Ixulescu"
                        },
                        new
                        {
                            Id = new Guid("a1111111-3333-3333-4444-555555555555"),
                            Birthday = new DateTime(1990, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Iox Axios"
                        });
                });

            modelBuilder.Entity("EmployeeManagement.Domain.Entities.EmployeePositions", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartedFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<float>("Salary")
                        .HasColumnType("real");

                    b.HasKey("EmployeeId", "PositionId", "StartedFrom");

                    b.HasIndex("PositionId");

                    b.ToTable("EmployeePositions");

                    b.HasData(
                        new
                        {
                            EmployeeId = new Guid("a1111111-1111-3333-4444-555555555555"),
                            PositionId = new Guid("b1111111-1111-3333-4444-555555555555"),
                            StartedFrom = new DateTime(2019, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Salary = 2000f
                        },
                        new
                        {
                            EmployeeId = new Guid("a1111111-2222-3333-4444-555555555555"),
                            PositionId = new Guid("b1111111-2222-3333-4444-555555555555"),
                            StartedFrom = new DateTime(2017, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndedAt = new DateTime(2018, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Salary = 2000f
                        },
                        new
                        {
                            EmployeeId = new Guid("a1111111-3333-3333-4444-555555555555"),
                            PositionId = new Guid("b1111111-3333-3333-4444-555555555555"),
                            StartedFrom = new DateTime(2017, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Salary = 2000f
                        });
                });

            modelBuilder.Entity("EmployeeManagement.Domain.Entities.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1111111-1111-3333-4444-555555555555"),
                            Department = "R&D",
                            Description = "Maintain software systems",
                            Title = "Programmer"
                        },
                        new
                        {
                            Id = new Guid("b1111111-2222-3333-4444-555555555555"),
                            Department = "HR",
                            Description = "Find right candidates for positions",
                            Title = "Talent Acquisition Manager"
                        },
                        new
                        {
                            Id = new Guid("b1111111-3333-3333-4444-555555555555"),
                            Department = "Marketing",
                            Description = "Create new content for social media",
                            Title = "Content Strategist"
                        });
                });

            modelBuilder.Entity("EmployeeManagement.Domain.Entities.EmployeePositions", b =>
                {
                    b.HasOne("EmployeeManagement.Domain.Entities.Employee", "Employee")
                        .WithMany("OwnedPositions")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmployeeManagement.Domain.Entities.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("EmployeeManagement.Domain.Entities.Employee", b =>
                {
                    b.Navigation("OwnedPositions");
                });
#pragma warning restore 612, 618
        }
    }
}
